# The API settings to use when making API requests
api-url: "http://127.0.0.1:4567/api/"
api-key: "test"

# The rank groups that are active on this server. Players that are assigned ranks that aren't active won't
# receive any of the permissions from that rank.
active-rank-groups: ['GLOBAL']