# The API settings to use when making API requests
api-url: "http://127.0.0.1:4567/api/"
api-key: "test"

# If set to true, chat messages will be formatted using the format specified at 'chat-format'.
format-chat: false

# The format of chat messages. The chat format supports the following placeholders:
chat-format: "{rankPrefix}%s&r: %s"

players:
  # Should we set the player's display name?
  set-display-name: false
  # The format for the player's display name.
  display-name-format: ""
  # Should we set the player's player-list name?
  set-player-list-name: false
  # The format for the player's player-list name.
  player-list-name-format: ""

# The rank groups that are active on this server. Players that are assigned ranks that aren't active won't
# receive any of the permissions from that rank.
active-rank-groups: ['GLOBAL']