name: CoreXD
version: 1.0
description: lol
author: joeleoli
main: com.minexd.core.bukkit.BukkitPlugin
depend:
  - Cubed
softdepend:
  - Vault
  - PlaceholderAPI
  - MVdWPlaceholderAPI
loadbefore: [Vault]