name: EvilPermissions
version: 1.0
description: Powerful permissions by simple design
author: joeleoli
main: net.evilblock.permissions.bukkit.BukkitPlugin
depend:
  - Cubed
softdepend:
  - PlaceholderAPI
  - MVdWPlaceholderAPI
loadbefore: [Vault]